[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "utils-mcp-server"
version = "0.1.0"
authors = [
  { name="PArisNeo", email="author@example.com" },
]
description = "An MCP server for basic utilities like time, weather, and crypto prices."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mcp-server-lib",
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
    "ascii-colors>=0.5.5",
]

[project.scripts]
utils-mcp-server = "utils_mcp_server.server:main_cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["utils_mcp_server*"]